services:
  - type: web
    name: telegram-chatgpt-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_token_here
      - key: OPENAI_API_KEY
        value: your_openai_key_here
